### PR TITLE
Updates to support sample size differences, channel mismatches and capturing render devices

### PR DESCRIPTION
**Pull request by cehbab**
Hi.

I've been using your project and updated it to support my needs.
I've fixed a couple of the issues in your Issues tracker, and one commenter asked could I offer a pull-request.

I've done my best to keep to as close to your logic as possible, defaulting to what you intended mono-to-stereo to accomplish, and adding parameters and fixes around that.

Mainly I wanted the following:
  Sample size changing support, 8, 16, 24, 32 between capture and render devices.
  Differing channel support, from mono, stereo, quad, 5.1, 7.1 to mono, stereo, quad, 5.1, 7.1 between devices.
  Some simple rules to clear out channels, swap, or copy.
  The ability to capture from a render device, using the SetWaitableTimer logic from loopback-capture.

Up to you, all I can do is offer :)

Cheers.

### CODE REVIEW

**Comment by ToadKing** [comment]
Hey nice work. I do not find myself using this application (or even Windows) very often these days so I'd rather not merge in and maintain stuff that I wouldn't actually test or use. I think just keeping all your changes in your own fork would be fine for now.

I may end up archiving this repo in a bit anyway just to make it obvious that it's not being actively maintained.

**Comment by cehbab** [comment]
Too easy, I had figured as much, and the pull request was on behalf of one of your users :)
It is interesting code though, I use it mainly for the el-cheapo hdmi dongle with an old xbox 360 plugged into my pc..
And to fiddle with sound, hence adding the ability to capture from render devices as well... just playing with it really. :)

I did take a look through your other repositories to see what you're interested in more recently.. :)

Cheers though.. and thanks.

**Comment by cehbab** [comment]
I'll have to figure out how to detach yours from upstream before I delete it.

Also, I added samplerate conversions as well... someone asked me for it, and it was pissing me off 2 weeks ago that I couldn't figure that out :).

I will detach the fork it though, and attribute you in the readme.

**Comment by ToadKing** [comment]
I won't be deleting the repo, I'll just be archiving it. You shouldn't have to detach it or anything.

**Pull request closed without merging**
