### PR TITLE
Set locale to system default

### PR DESCRIPTION
**Pull request by kilinbox**

### CODE REVIEW

**Comment by ToadKing** [comment]
What exactly does this fix?

**Comment by kilinbox** [comment]
sorry, I guess I didn't explain myself well enough.
Non-enｰUS operating systems, Cannot read the Device Name. "Mojibake (garbled text)"
screen

**Comment by ToadKing** [comment]
Ah, that make sense.

This change seems to work, but only if you have the correct character code page set which isn't guaranteed depending on your locale. I think a better solution is to not use the C standard library for output and to just use the native Win32 calls, which seem to work on my end at least.

image

Can you try this build and see if it also works for you?

[unicode-fix.zip](https://github.com/ToadKing/mono-to-stereo/files/5248907/unicode-fix.zip)

**Comment by kilinbox** [comment]
checked "unicode-fix"
It worked! Thank you!
unicode-fix

**Comment by ToadKing** [comment]
Great. I'll close this PR then. The latest 0.5 release should have this fix in it.

**Pull request closed without merging**
